In [5]:
import duckdb
import pandas as pd
import os

# üìÅ Ordner mit deinen Excel-Dateien
folder = 
file_paths = [os.path.join(folder, f) for f in os.listdir(folder) if f.endswith((".xlsx", ".xls"))]

# üíæ DuckDB-Verbindung
con = duckdb.connect("qttr.db")

# üìä Alle Dateien in Tabellen schreiben
for path in file_paths:
    table_name = os.path.splitext(os.path.basename(path))[0].lower()
    df = pd.read_excel(path).astype(str)
    con.register("temp_df", df)
    con.execute(f"CREATE OR REPLACE TABLE '{table_name}' AS SELECT * FROM temp_df")
    con.unregister("temp_df")

print("Alle Excel-Dateien aus dem Ordner wurden in DuckDB gespeichert.")

SyntaxError: invalid syntax (484695683.py, line 6)

In [7]:
import duckdb
import pandas as pd

con = duckdb.connect("qttr.db")

tabellen = con.execute("SHOW TABLES").fetchdf()["name"].tolist()
tabellen

['q-ttr-liste_20101201_komplett',
 'q-ttr-liste_20110301_komplett',
 'q-ttr-liste_20110511_komplett',
 'q-ttr-liste_20110811_komplett',
 'q-ttr-liste_20111211_komplett',
 'q-ttr-liste_20120211_komplett',
 'q-ttr-liste_20120511_komplett',
 'q-ttr-liste_20120811_komplett',
 'q-ttr-liste_20121211_komplett',
 'q-ttr-liste_20130211_komplett',
 'q-ttr-liste_20130511_komplett',
 'q-ttr-liste_20130811_komplett',
 'q-ttr-liste_20131211_komplett',
 'q-ttr-liste_20140211_komplett',
 'q-ttr-liste_20140511_komplett',
 'q-ttr-liste_20140811_komplett',
 'q-ttr-liste_20141211_komplett',
 'q-ttr-liste_20150211_komplett',
 'q-ttr-liste_20150511 komplett',
 'q-ttr-liste_20150811_komplett',
 'q-ttr-liste_20151211_komplett',
 'q-ttr-liste_20160211_komplett',
 'q-ttr-liste_20160511_komplett',
 'q-ttr-liste_20160811_komplett',
 'q-ttr-liste_20161211_komplett',
 'q-ttr-liste_20170211_komplett',
 'q-ttr-liste_20170511_komplett',
 'q-ttr-liste_20170811_komplett',
 'q-ttr-liste_20171211_komplett',
 'q-ttr-liste_20180211_komplett',
 'q-ttr-liste_20180511_komplett',
 'q-ttr-liste_20180811_komplett',
 'q-ttr-liste_20181211_komplett',
 'q-ttr-liste_20190211_komplett',
 'q-ttr-liste_20190511_komplett',
 'q-ttr-liste_20190811_komplett',
 'q-ttr-liste_20191211_komplett',
 'q-ttr-liste_20200211_komplett',
 'q-ttr-liste_20200511_komplett',
 'q-ttr-liste_20200811_komplett',
 'q-ttr-liste_20201211_komplett',
 'q-ttr-liste_20210211_komplett',
 'q-ttr-liste_20210511_komplett',
 'q-ttr-liste_20210811_komplett',
 'q-ttr-liste_20211211_komplett',
 'q-ttr-liste_20220211_komplett',
 'q-ttr-liste_20220511_komplett',
 'q-ttr-liste_20220811_komplett',
 'q-ttr-liste_20221211_komplett',
 'q-ttr-liste_20230211_komplett',
 'q-ttr-liste_20230511_komplett',
 'q-ttr-liste_20230811_komplett',
 'q-ttr-liste_20231211_komplett',
 'q-ttr-liste_20240211_komplett',
 'q-ttr-liste_20240511_komplett',
 'q-ttr-liste_20240811_komplett',
 'q-ttr-liste_20241211_komplett',
 'q-ttr-liste_20250211_komplett']

In [26]:
spalten = con.execute("PRAGMA table_info('q-ttr-liste_20250211_komplett')").fetchdf()
spalten

    cid                           name     type  notnull dflt_value     pk
0     0                      InterneNr  VARCHAR    False       None  False
1     1                       Nachname  VARCHAR    False       None  False
2     2                        Vorname  VARCHAR    False       None  False
3     3       GeschlechtImSpielbetrieb  VARCHAR    False       None  False
4     4                         Nation  VARCHAR    False       None  False
5     5                              A  VARCHAR    False       None  False
6     6         Einstufungsart zuletzt  VARCHAR    False       None  False
7     7      Einstufungsgruppe zuletzt  VARCHAR    False       None  False
8     8    Einstufungsposition zuletzt  VARCHAR    False       None  False
9     9                     Verstorben  VARCHAR    False       None  False
10   10                         Status  VARCHAR    False       None  False
11   11                        Verband  VARCHAR    False       None  False
12   12                         Bezirk  VARCHAR    False       None  False
13   13                          Kreis  VARCHAR    False       None  False
14   14                         Verein  VARCHAR    False       None  False
15   15                   Altersklasse  VARCHAR    False       None  False
16   16                    Spielklasse  VARCHAR    False       None  False
17   17                  Spielposition  VARCHAR    False       None  False
18   18                             Nr  INTEGER    False       None  False
19   19                           Rang  INTEGER    False       None  False
20   20                 Deutscher Rang  INTEGER    False       None  False
21   21        Einstufungswert zuletzt  INTEGER    False       None  False
22   22                            TTR  INTEGER    False       None  False
23   23           Anzahl Einzel gesamt  INTEGER    False       None  False
24   24  Kumulierte Inaktivit√§tsabz√ºge  INTEGER    False       None  False
25   25          Kumulierte QNSZ-Werte  INTEGER    False       None  False
26   26          Kumulierte QNEB-Werte  INTEGER    False       None  False
27   27                             2J  INTEGER    False       None  False
28   28                           lebt  INTEGER    False       None  False
29   29                             MM  INTEGER    False       None  False
30   30                            spb  INTEGER    False       None  False
31   31                            10E  INTEGER    False       None  False
32   32                            Typ  INTEGER    False       None  False
33   33                   Geburtsdatum     DATE    False       None  False
34   34                  Letztes Spiel     DATE    False       None  False
35   35       Einstufungsdatum zuletzt     DATE    False       None  False

In [13]:
spalten['name'].tolist()

['Rang',
 'Deutscher Rang',
 'InterneNr',
 'Nachname',
 'Vorname',
 'GeschlechtImSpielbetrieb',
 'Geburtsdatum',
 'Nation',
 'A',
 'Einstufungsart zuletzt',
 'Einstufungsdatum zuletzt',
 'Einstufungswert zuletzt',
 'Einstufungsgruppe zuletzt',
 'Einstufungsposition zuletzt',
 'Anzahl Einzel gesamt',
 'TTR',
 'Kumulierte Inaktivit√§tsabz√ºge',
 'Kumulierte QNSZ-Werte',
 'Kumulierte QNEB-Werte',
 'Letztes Spiel',
 'Verstorben',
 'Status',
 '2J',
 'lebt',
 'MM',
 'spb',
 '10E',
 'Typ',
 'Verband',
 'Bezirk',
 'Kreis',
 'Verein',
 'Altersklasse',
 'Spielklasse',
 'Spielposition',
 'Nr']

In [25]:
#spalten = ["Rang",'Deutscher Rang', 'Einstufungswert zuletzt', 'TTR','Anzahl Einzel gesamt','Kumulierte Inaktivit√§tsabz√ºge','Kumulierte QNSZ-Werte','Kumulierte QNEB-Werte', '2J','lebt','MM','spb','10E','Typ']  # Liste der Spalten, die umgewandelt werden sollen
spalten = ["Einstufungsdatum zuletzt"]

for tabelle in tabellen:
    spalten_liste = con.execute(f"PRAGMA table_info('{tabelle}')").fetchdf()["name"].tolist()

    for spalte in spalten:
        if spalte in spalten_liste:
            
            con.execute(f"""
                CREATE OR REPLACE TABLE "{tabelle}" AS
                SELECT 
                    *, 
                    TRY_CAST("{spalte}" AS DATE) AS "{spalte}_neu"
                FROM "{tabelle}"
            """) 
            
            con.execute(f"""ALTER TABLE "{tabelle}" DROP COLUMN "{spalte}";""")
            con.execute(f"""ALTER TABLE "{tabelle}" RENAME COLUMN "{spalte}_neu" TO "{spalte}";""")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [27]:
pd.set_option("display.max_columns", None)  # Zeige alle Spalten
pd.set_option("display.width", None)        # Keine feste Breite
pd.set_option("display.max_colwidth", None)

showcase = con.execute(f'SELECT * FROM "{tabellen[-1]}" LIMIT 50').fetchdf()
showcase

,InterneNr,Nachname,Vorname,GeschlechtImSpielbetrieb,Nation,A,Einstufungsart zuletzt,Einstufungsgruppe zuletzt,Einstufungsposition zuletzt,Verstorben,Status,Verband,Bezirk,Kreis,Verein,Altersklasse,Spielklasse,Spielposition,Nr,Rang,Deutscher Rang,Einstufungswert zuletzt,TTR,Anzahl Einzel gesamt,Kumulierte Inaktivit√§tsabz√ºge,Kumulierte QNSZ-Werte,Kumulierte QNEB-Werte,2J,lebt,MM,spb,10E,Typ,Geburtsdatum,Letztes Spiel,Einstufungsdatum zuletzt
0,NU1465760,Fan,Zhendong,M,CHN,A,T,15.07.2012: Asian Junior & Cadet Championships 2012 - Jungen,nan,nein,a,Ausland,Ausland,Ausland,China,nan,nan,nan,1,1,<NA>,2726,2782,525,0,60,84,1,1,0,1,1,28,1997-01-22,2024-08-05,2012-07-15
1,NU1466103,Wang,Chuqin,M,CHN,A,T,23.09.2012: Chengdu (China) Junior & Cadet Open 2012 - Jungen,nan,nein,a,Ausland,Ausland,Ausland,China,nan,nan,nan,2,2,<NA>,2739,2750,382,0,138,266,1,1,0,1,1,28,2000-05-11,2024-11-20,2012-09-23
2,NU2109031,Lin,Shidong,M,CHN,A,T,12.09.2018: Croatia Junior & Cadet Open - Jungen,nan,nein,a,Ausland,Ausland,Ausland,China,nan,nan,nan,3,3,<NA>,2291,2745,212,0,114,196,1,1,0,1,1,28,2005-04-18,2024-11-20,2018-09-12
3,NU1227002,Ma,Long,M,CHN,A,T,10.09.2006: Pro Tour VOLKSWAGEN Singapore Open 2006 - Herren,nan,nein,a,Ausland,Ausland,Ausland,China,nan,nan,nan,4,4,<NA>,2648,2713,700,0,6,0,1,1,0,1,1,28,1988-10-20,2024-09-26,2006-09-10
4,NU2045961,Lebrun,Felix,M,FRA,eA,T,14.02.2018: Czech Junior & Cadet Open - Jungen,nan,nein,a,Ausland,Ausland,Ausland,France,nan,nan,nan,5,5,<NA>,2179,2702,340,0,156,308,1,1,0,1,1,28,2006-09-12,2024-11-20,2018-02-14
5,NU1464247,Liang,Jingkun,M,CHN,A,T,07.08.2011: Hong Kong Junior & Cadet Open 2011 - Jungen,nan,nein,a,Ausland,Ausland,Ausland,China,nan,nan,nan,6,6,<NA>,2462,2688,348,0,78,126,1,1,0,1,1,28,1996-10-20,2024-11-20,2011-08-07
6,NU1604428,Harimoto,Tomokazu,M,JPN,A,T,06.08.2014: Hong Kong Junior & Cadet Open - Jungen,nan,nein,a,Ausland,Ausland,Ausland,Japan,nan,nan,nan,7,7,<NA>,2357,2686,509,0,162,322,1,1,0,1,1,28,2003-06-27,2025-01-11,2014-08-06
7,NU1646298,Sun,Yingsha,W,CHN,A,T,12.09.2014: 2014 Asian Junior and Cadet Championships - M√§dchen,nan,nein,a,Ausland,Ausland,Ausland,China,nan,nan,nan,8,8,<NA>,2430,2681,369,0,102,182,1,1,0,1,1,28,2000-11-04,2024-11-20,2014-09-12
8,NU1461170,Calderano,Hugo,M,POR,eA,T,19.06.2009: 14th Latin American Cadet Championships 2009 - Sch√ºler,nan,nein,a,TTBW,TTBW,Donau,TTF Liebherr Ochsenhausen,Herren,1. Bundesliga,2025-01-01 00:00:00,9,9,<NA>,2021,2668,1104,0,120,224,1,1,1,1,1,32,1996-06-22,2025-01-27,2009-06-19
9,NU1466173,Lin,Yun-Ju,M,TPE,A,T,28.07.2013: Chinese Taipei Junior & Cadet Open 2013 - Jungen,nan,nein,a,Ausland,Ausland,Ausland,Japan,nan,nan,nan,10,10,<NA>,2348,2665,587,0,144,280,1,1,0,1,1,28,2001-08-17,2024-11-20,2013-07-28
10,NU1487180,M√∂regardh,Truls,M,SWE,eA,T,24.02.2013: Swedish Junior & Cadet Open 2013 - Sch√ºler,nan,nein,a,Ausland,Ausland,Ausland,Sweden,nan,nan,nan,11,11,<NA>,1806,2657,538,0,168,336,1,1,0,1,1,28,2002-02-16,2024-11-20,2013-02-24
11,NU1465792,Wang,Manyu,W,CHN,A,T,15.07.2012: Asian Junior & Cadet Championships 2012 - Sch√ºlerinnen,nan,nein,a,Ausland,Ausland,Ausland,China,nan,nan,nan,12,12,<NA>,2376,2656,373,0,108,196,1,1,0,1,1,28,1999-02-09,2024-11-20,2012-07-15
12,NU1227019,Lin,Gaoyuan,M,CHN,A,T,26.07.2009: Asian Junior & Cadet Championships 2009 - Sch√ºler,nan,nein,a,Ausland,Ausland,Ausland,China,nan,nan,nan,13,13,<NA>,2491,2647,400,0,84,140,1,1,0,1,1,28,1995-03-19,2024-11-20,2009-07-26
13,NU1227220,Chen,Meng,W,CHN,A,T,20.01.2007: Australian Youth Olympic Festival 2007 - M√§dchen,nan,nein,a,Ausland,Ausland,Ausland,China,nan,nan,nan,14,14,<NA>,2294,2646,480,0,120,224,1,1,0,1,1,28,1994-01-15,2024-07-27,2007-01-20
14,NU1462405,K√§llberg,Anton,M,SWE,eA,T,27.02.2011: Safir Junior Open 2011 - Sch√ºler,nan,nein,a,Nordrhein-Westfalen,Nordrhein-Westfalen,Rhein-Wupper,Borussia D√ºsseldorf,Herren,1. Bundesliga,2025-02-01 00:00:00,15,15,<NA>,2043,2644,989,0,108,196,1,1,1,1,1,32,1997-08-17,2025-02-09,2011-02-27
15,NU1769687,Lebrun,Alexis,M,FRA,eA,T,30.10.2015: Slovak Cadet Open - Sch√ºler,nan,nein,a,Ausland,Ausland,Ausland,France,nan,nan,nan,16,16,<NA>,1934,2644,266,0,138,266,1,1,0,1,1,28,2003-08-27,2024-11-20,2015-10-30
16,NU1464246,Zhou,Qihao,M,CHN,A,T,24.07.2011: Asian Junior Championships 2011 - Sch√ºler,nan,nein,a,Ausland,Ausland,Ausland,China,nan,nan,nan,17,17,<NA>,2629,2644,245,0,84,140,1,1,0,1,1,28,1997-01-12,2024-11-23,2011-07-24
17,NU7535,Qiu,Dang,M,GER,nan,S,Jungen U18 Bezirksklasse,2.0,nein,a,Nordrhein-Westfalen,Nordrhein-Westfalen,Rhein-Wupper,Borussia D√ºsseldorf,Herren,1. Bundesliga,2025-01-01 00:00:00,18,18,1,1340,2640,1533,0,222,0,1,1,1,1,1,32,1996-10-29,2025-01-13,2005-09-16
18,NU94325,Ovtcharov,Dimitrij,M,GER,nan,S,1. Bundesliga Herren,3.0,nein,a,Hessen,Bezirk Mitte,Fulda,TTC Rh√∂nSprudel Fulda-Maberzell,Herren,1. Bundesliga,2025-01-01 00:00:00,19,19,2,2500,2624,1076,0,24,0,1,1,1,1,1,32,1988-09-02,2025-01-25,2005-08-28
19,NU1943654,Chen,Yuanyu,M,CHN,A,T,21.06.2017: China Junior & Cadet Open - Jungen,nan,nein,a,Ausland,Ausland,Ausland,China,nan,nan,nan,20,20,<NA>,2259,2624,260,0,150,294,1,1,0,1,1,28,2005-07-06,2025-01-11,2017-06-21
20,NU2081407,Matsushima,Sora,M,JPN,A,T,01.08.2018: Hong Kong Junior&Cadet Open - Jungen,nan,nein,a,Ausland,Ausland,Ausland,Japan,nan,nan,nan,21,21,<NA>,2210,2618,347,0,156,322,1,1,0,1,1,28,2007-04-29,2025-01-11,2018-08-01
21,NU2457339,Wen,Ruibo,M,CHN,A,T,04.12.2022: ITTF World Youth Team Championships 2022 - Jungen 15,nan,nein,a,Ausland,Ausland,Ausland,China,nan,nan,nan,22,22,<NA>,2383,2607,138,0,54,70,1,1,0,1,1,28,2007-01-05,2024-11-26,2022-12-04
22,NU1261419,Jang,Woojin,M,KOR,A,T,08.02.2009: ITTF WJC - Bahrain Junior Open 2009 - Jungen,nan,nein,a,Ausland,Ausland,Ausland,South Korea (Republic),nan,nan,nan,23,23,<NA>,2339,2605,620,0,102,140,1,1,0,1,1,28,1995-09-10,2024-11-20,2009-02-08
23,NU2498935,Sun,Yang,M,CHN,A,T,27.03.2023: WTT Youth Contender Berlin 2023 Jungen - Jungen 17,nan,nein,a,Ausland,Ausland,Ausland,China,nan,nan,nan,24,24,<NA>,2402,2605,126,0,48,112,1,1,0,1,1,28,2008-02-28,2024-10-03,2023-03-27
24,NU1829889,Togami,Shunsuke,M,JPN,A,T,19.05.2016: Slovak Junior Open - ITTF Junior Circuit - Jungen,nan,nein,a,TTBW,TTBW,Donau,TTF Liebherr Ochsenhausen,Herren,1. Bundesliga,2025-02-01 00:00:00,25,25,<NA>,2281,2601,378,0,78,126,1,1,1,1,1,32,2001-08-24,2025-01-12,2016-05-19
25,NU2045862,Xiang,Peng,M,CHN,A,T,07.02.2018: Oman Junior & Cadet Open - Jungen,nan,nein,a,Ausland,Ausland,Ausland,China,nan,nan,nan,26,26,<NA>,2403,2600,298,0,72,112,1,1,0,1,1,28,2003-03-07,2025-01-11,2018-02-07
26,NU1260178,Groth,Jonathan,M,DEN,eA,T,03.06.2007: ITTF WJC - 14th Polish Youth Open 2007 - Jungen,nan,nein,a,Ausland,Ausland,Ausland,Russia,nan,nan,nan,27,27,<NA>,2100,2593,884,0,84,140,1,1,0,1,1,28,1992-11-09,2025-01-06,2007-06-03
27,NU1465762,Liu,Dingshuo,M,CHN,A,T,15.07.2012: Asian Junior & Cadet Championships 2012 - Sch√ºler,nan,nein,a,Ausland,Ausland,Ausland,China,nan,nan,nan,28,28,<NA>,2568,2590,199,0,84,140,1,1,0,1,1,28,1998-01-13,2024-05-21,2012-07-15
28,NU1466061,An,Jaehyeon,M,KOR,A,T,01.09.2012: Korea Junior & Cadet Open 2012 - Sch√ºler,nan,nein,a,Bayern,Bayern,Schwaben-Nord,TTC Neu-Ulm e.V.,nan,nan,nan,29,29,<NA>,2352,2586,452,0,126,238,1,1,0,0,1,26,1999-12-25,2024-11-03,2012-09-01
29,NU2109024,Huang,Youzheng,M,CHN,A,T,12.09.2018: Croatia Junior & Cadet Open - Jungen,nan,nein,a,Ausland,Ausland,Ausland,China,nan,nan,nan,30,30,<NA>,2317,2585,192,0,114,196,1,1,0,1,1,28,2005-06-09,2025-01-11,2018-09-12
30,NU1465797,Chen,Xingtong,W,CHN,A,T,15.07.2012: Asian Junior & Cadet Championships 2012 - Sch√ºlerinnen,nan,nein,a,Ausland,Ausland,Ausland,China,nan,nan,nan,31,31,<NA>,2348,2580,306,0,66,98,1,1,0,1,1,28,1997-05-27,2024-11-20,2012-07-15
31,NU218453,Duda,Benedikt,M,GER,nan,S,Jungen-Verbandsliga,3.0,nein,a,Nordrhein-Westfalen,Nordrhein-Westfalen,K√∂ln,TTC Schwalbe Bergneustadt,Herren,1. Bundesliga,2025-02-01 00:00:00,32,32,3,1520,2578,1659,0,138,0,1,1,1,1,1,32,1994-04-04,2025-01-26,2006-09-02
32,NU1458481,Wong,Chun Ting,M,HKG,A,T,30.07.2007: 13th Asian Junior Championships 2007 - Jungen,nan,nein,a,Hessen,Bezirk Mitte,Fulda,TTC Rh√∂nSprudel Fulda-Maberzell,nan,nan,nan,33,33,<NA>,1858,2577,614,0,48,56,1,1,0,1,1,28,1991-09-07,2025-01-11,2007-07-30
33,NU1604491,Wang,Yidi,W,CHN,A,T,23.06.2014: China Junior & Cadet Open - M√§dchen,nan,nein,a,Ausland,Ausland,Ausland,China,nan,nan,nan,34,34,<NA>,2232,2576,304,0,18,0,1,1,0,1,1,28,1997-02-14,2024-11-20,2014-06-23
34,NU1463841,Jorgic,Darko,M,SLO,eA,T,06.03.2011: Italian Junior & Cadet Open 2011 - Sch√ºler,nan,nein,a,Saarland,Bezirk S√ºd-West,Kreis S√ºdsaar,1. FC Saarbr√ºcken-TT,Herren,1. Bundesliga,2025-01-01 00:00:00,35,35,<NA>,1835,2573,1110,0,132,252,1,1,1,1,1,32,1998-07-30,2025-02-09,2011-03-06
35,NU1772184,Kao,Cheng-Jui,M,TPE,A,T,24.08.2016: Chines Taipei Junior&Cadet Open - Jungen,nan,nein,a,Hessen,Bezirk Mitte,Fulda,TTC Rh√∂nSprudel Fulda-Maberzell,Herren,1. Bundesliga,2025-02-01 00:00:00,36,36,<NA>,2005,2571,244,0,150,294,1,1,1,1,1,32,2004-12-25,2024-12-15,2016-08-24
36,NU1604420,Cho,Daeseong,M,KOR,A,T,11.06.2014: Korea Open - Herren,nan,nein,a,Ausland,Ausland,Ausland,South Korea (Republic),nan,nan,nan,37,37,<NA>,2225,2570,358,0,156,308,1,1,0,1,1,28,2002-10-13,2025-01-06,2014-06-11
37,NU1464463,Yu,Ziyang,M,CHN,A,T,24.07.2011: Asian Junior Championships 2011 - Sch√ºler,nan,nein,a,Ausland,Ausland,Ausland,China,nan,nan,nan,38,38,<NA>,2517,2570,171,0,114,210,1,1,0,1,1,28,1998-05-23,2023-11-22,2011-07-24
38,NU1465780,Xue,Fei,M,CHN,A,T,15.07.2012: Asian Junior & Cadet Championships 2012 - Sch√ºler,nan,nein,a,Ausland,Ausland,Ausland,China,nan,nan,nan,39,39,<NA>,2601,2569,238,0,108,196,1,1,0,1,1,28,1999-02-10,2024-11-23,2012-07-15
39,NU1911451,Shinozuka,Hiroto,M,JPN,A,T,08.02.2017: Czech Junior & Cadet Open - Jungen,nan,nein,a,Ausland,Ausland,Ausland,Japan,nan,nan,nan,40,40,<NA>,2223,2565,338,0,114,210,1,1,0,1,1,28,2003-12-23,2025-01-11,2017-02-08
40,NU2655614,Ning,Xiankun,M,CHN,A,T,19.06.2024: WTT Contender Lagos 2024 - Herren,nan,nein,a,Ausland,Ausland,Ausland,China,nan,nan,nan,41,41,<NA>,2557,2565,16,0,18,28,1,1,0,1,1,28,2007-11-20,2024-11-06,2024-06-19
41,NU1227052,Lee,Sangsu,M,KOR,A,T,30.07.2006: 12th Asian Junior Championships 2006 - Jungen,nan,nein,a,Ausland,Ausland,Ausland,South Korea (Republic),nan,nan,nan,42,42,<NA>,2340,2563,618,0,48,56,1,1,0,1,1,28,1990-08-13,2024-09-26,2006-07-30
42,NU1943667,Kuai,Man,W,CHN,A,T,21.06.2017: China Junior & Cadet Open - M√§dchen,nan,nein,a,Ausland,Ausland,Ausland,China,nan,nan,nan,43,43,<NA>,2246,2563,285,0,114,210,1,1,0,1,1,28,2004-02-07,2025-01-11,2017-06-21
43,NU1646288,Xu,Yingbin,M,CHN,A,T,12.09.2014: 2014 Asian Junior and Cadet Championships - Jungen,nan,nein,a,Ausland,Ausland,Ausland,China,nan,nan,nan,44,44,<NA>,2290,2563,282,0,108,196,1,1,0,1,1,28,2001-03-12,2025-01-11,2014-09-12
44,NU1845016,Song,Zhuoheng,M,CHN,A,T,22.07.2016: China Junior & Cadet Open - Jungen,nan,nein,a,Ausland,Ausland,Ausland,China,nan,nan,nan,45,45,<NA>,2336,2563,74,0,96,168,1,1,0,1,1,28,2002-08-15,2023-08-30,2016-07-22
45,NU59787,Franziska,Patrick,M,GER,nan,S,Oberliga Herren,3.0,nein,a,Saarland,Bezirk S√ºd-West,Kreis S√ºdsaar,1. FC Saarbr√ºcken-TT,Herren,1. Bundesliga,2025-02-01 00:00:00,46,46,4,1960,2562,1420,0,114,0,1,1,1,1,1,32,1992-06-11,2025-02-09,2005-09-25
46,NU1559117,Uda,Yukiya,M,JPN,A,T,04.08.2013: Korea Junior & Cadet Open 2013 - Sch√ºler,nan,nein,a,Ausland,Ausland,Ausland,Japan,nan,nan,nan,47,47,<NA>,2153,2562,607,0,144,224,1,1,0,1,1,28,2001-08-06,2025-01-06,2013-08-04
47,NU1227117,Gauzy,Simon,M,FRA,eA,T,25.02.2007: ITTF WJC - Safir International Junior Open 2007 - Jungen,nan,nein,a,TTBW,TTBW,Donau,TTF Liebherr Ochsenhausen,Herren,1. Bundesliga,2025-03-01 00:00:00,48,48,<NA>,1963,2560,1146,0,138,266,1,1,1,1,1,32,1994-10-25,2025-01-27,2007-02-25
48,NU1227039,Yoshimura,Maharu,M,JPN,A,T,09.05.2010: Spanish Junior & Cadet Open 2010 - Jungen,nan,nein,a,Ausland,Ausland,Ausland,Japan,nan,nan,nan,49,49,<NA>,2388,2560,462,0,30,14,1,1,0,1,1,28,1993-08-03,2025-01-11,2010-05-09
49,NU1462330,Lind,Anders,M,DEN,eA,T,28.02.2010: Swedish Junior & Cadet Open 2010 - Sch√ºler,nan,nein,a,Nordrhein-Westfalen,Nordrhein-Westfalen,Mittleres Ruhrgebiet,BV Borussia 09 Dortmund,Herren,1. Bundesliga,2025-01-01 00:00:00,50,50,<NA>,1810,2559,642,0,162,322,1,1,1,1,1,32,1998-12-14,2025-02-10,2010-02-28